version: 2.1

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.10.2
    steps:
      - checkout
      - run:
          name: activate environnement / install packages
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - run:
          name: linting
          command: |
            . venv/bin/activate
            flake8
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            pytest
  containerize:
    docker:
      - image: cimg/python:3.10.2
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Containerize
          command: |
            echo "$DOCKER_PASSWORD" | docker login --username $DOCKER_LOGIN --password-stdin
            docker build -t image_oc_lettings_site .
            docker tag image_oc_lettings_site $DOCKER_LOGIN/$DOCKER_REPO:$CIRCLE_SHA1
            docker push $DOCKER_LOGIN/$DOCKER_REPO:$CIRCLE_SHA1
  deployment:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "Deploy"
          command: curl -X GET $RENDER_HOOK
workflows:
  main:
    jobs:
      - build-and-test
      - containerize:
          requires:
            - build-and-test
          filters:
            branches:
              only:
                - master
      - deployment:
          requires:
            - build-and-test
            - containerize
          filters:
            branches:
              only:
                - master


