# Generated by Django 3.0 on 2023-07-29 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oc_lettings_site', '0001_initial'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='letting',
        #     name='address',
        # ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.RemoveField(
                    model_name="letting",
                    name="address",
                )
            ],
        ),

        
        # migrations.RemoveField(
        #     model_name='profile',
        #     name='user',
        # ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.RemoveField(
                    model_name="profile",
                    name="user",
                )
            ],
        ),

        # migrations.DeleteModel(
        #     name='Address',
        # ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.AlterModelTable(
                    name='Address',
                    table='lettings_address',
                )
            ],
            state_operations=[
                migrations.DeleteModel(
                    name='Address'
                )
            ],
        ),
        

        # migrations.DeleteModel(
        #     name='Letting',
        # ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.AlterModelTable(
                    name='Letting',
                    table='lettings_letting',
                )
            ],
            state_operations=[
                migrations.DeleteModel(
                    name='Letting'
                )
            ],
        ),

        # migrations.DeleteModel(
        #     name='Profile',
        # ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.AlterModelTable(
                    name='Profile',
                    table='profiles_profile',
                )
            ],
            state_operations=[
                migrations.DeleteModel(
                    name='Profile'
                )
            ],
        ),

    ]
